name: malta_taxi
description: A new Flutter project.
version: 1.4.5+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0+1
  animations: ^2.0.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  change_app_package_name: ^1.1.0
  connectivity_plus: null
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.0
  easy_localization: ^3.0.3
  flextras: ^1.0.0
  floating: ^2.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_dotenv: ^5.0.2
  flutter_html: null
  flutter_image_stack: ^0.0.6
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get_it: ^7.2.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.5.0
  iconly: ^1.0.1
  image_picker: ^1.0.1
  injectable: null
  intl: ^0.18.0
  live_activities: ^1.7.5
  lottie: ^2.6.0
  outline_gradient_button: ^2.0.0+1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^8.0.1
  pinput: ^3.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.9
  webview_flutter: ^4.4.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/languages/
    - assets/images/
    - assets/icons/
    - assets/icons/car/
    - assets/flag/
    - assets/banner/
    - assets/animations/
    - assets/icons/maps/
    - assets/maps/maps.json
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf
          weight: 600
